"""
Konfigurasjon for Navigr - 10 største selskaper på Oslo Børs.

Brukerne starter med alle 10 som ankerflåte. De kan ta opp anker
og kaste anker for å tilpasse sin egen flåte.
"""

COMPANIES = {
    "EQNR": {
        "name": "Equinor ASA",
        "yahoo_ticker": "EQNR.OL",
        "sector": "Energi",
        "logo": "EQ",
        "about": "Equinor ASA er Norges største energiselskap, med hovedkontor i Stavanger. Selskapet driver med leting, produksjon, transport, foredling og markedsføring av petroleum og petroleumsbaserte produkter, samt fornybar energi som havvind. Norske staten eier 67 % av selskapet.",
        "hq": "Stavanger",
        "founded": "1972",
        "employees": "23 100",
    },
    "DNB": {
        "name": "DNB Bank ASA",
        "yahoo_ticker": "DNB.OL",
        "sector": "Finans",
        "logo": "DN",
        "about": "DNB Bank ASA er Norges største finanskonsern og en av de største bankene i Norden. Selskapet tilbyr personmarked- og bedriftstjenester, kapitalforvaltning og forsikring. DNB eier 47 % av Vipps MobilePay og kjøpte nylig meglerhuset Carnegie.",
        "hq": "Bjørvika, Oslo",
        "founded": "1822",
        "employees": "10 200",
    },
    "AKRBP": {
        "name": "Aker BP ASA",
        "yahoo_ticker": "AKRBP.OL",
        "sector": "Energi",
        "logo": "AK",
        "about": "Aker BP ASA er et norsk olje- og gasselskap som driver utelukkende på norsk sokkel. Selskapet er en av de største operatørene på norsk sokkel og har lavest produksjonskostnad i bransjen. Johan Sverdrup-feltet er det viktigste produksjonsfeltet.",
        "hq": "Fornebu",
        "founded": "2016",
        "employees": "2 100",
    },
    "NHY": {
        "name": "Norsk Hydro ASA",
        "yahoo_ticker": "NHY.OL",
        "sector": "Industri",
        "logo": "NH",
        "about": "Norsk Hydro ASA er et globalt aluminiums- og fornybarselskap. Selskapet driver hele verdikjeden fra bauksitt-utvinning til produksjon av aluminium, samt strømproduksjon fra vannkraft. Den norske staten eier 34 % av selskapet.",
        "hq": "Vækerø, Oslo",
        "founded": "1905",
        "employees": "34 000",
    },
    "TEL": {
        "name": "Telenor ASA",
        "yahoo_ticker": "TEL.OL",
        "sector": "Telekom",
        "logo": "TE",
        "about": "Telenor ASA er et norsk telekomselskap som driver virksomhet i Norden og Asia. Selskapet leverer mobil- og fasttjenester til over 200 millioner kunder. Norske staten er hovedeier med 54 %.",
        "hq": "Fornebu",
        "founded": "1855",
        "employees": "15 600",
    },
    "YAR": {
        "name": "Yara International ASA",
        "yahoo_ticker": "YAR.OL",
        "sector": "Industri",
        "logo": "YA",
        "about": "Yara International ASA er en av verdens største produsenter av mineralgjødsel. Selskapet driver virksomhet i over 60 land og har som mål å være karbonnøytrale innen 2050.",
        "hq": "Vækerø, Oslo",
        "founded": "1905",
        "employees": "17 800",
    },
    "MOWI": {
        "name": "Mowi ASA",
        "yahoo_ticker": "MOWI.OL",
        "sector": "Sjømat",
        "logo": "MO",
        "about": "Mowi ASA er verdens største oppdrettsselskap for atlantisk laks. Selskapet driver i Norge, Skottland, Canada, Chile, Færøyene og Irland og er fullt vertikalt integrert.",
        "hq": "Bergen",
        "founded": "1964",
        "employees": "15 000",
    },
    "STB": {
        "name": "Storebrand ASA",
        "yahoo_ticker": "STB.OL",
        "sector": "Finans",
        "logo": "ST",
        "about": "Storebrand ASA er et nordisk forsikrings- og finanskonsern som tilbyr pensjon, livsforsikring, skadeforsikring, bank og kapitalforvaltning. Selskapet er en av Nordens største kapitalforvaltere med over 1 000 milliarder i forvaltningskapital.",
        "hq": "Lysaker",
        "founded": "1767",
        "employees": "2 200",
    },
    "SUBC": {
        "name": "Subsea 7 SA",
        "yahoo_ticker": "SUBC.OL",
        "sector": "Energi",
        "logo": "S7",
        "about": "Subsea 7 SA er et globalt selskap som leverer subsea-konstruksjon for olje- og gassindustrien og fornybarindustrien til havs. Hovedfokuset er på dypvannsutbygging og havvind-installasjoner.",
        "hq": "Luxembourg",
        "founded": "2002",
        "employees": "12 000",
    },
    "SCATC": {
        "name": "Scatec ASA",
        "yahoo_ticker": "SCATC.OL",
        "sector": "Fornybar energi",
        "logo": "SC",
        "about": "Scatec ASA er et norsk uavhengig kraftprodusent som utvikler, bygger, eier og driver solcelleparker, vannkraftverk og batterilagre. Selskapet har virksomhet i over 15 land med fokus på fremvoksende markeder.",
        "hq": "Karenslyst, Oslo",
        "founded": "2007",
        "employees": "700",
    },
}

INITIAL_FLEET = ["EQNR", "DNB", "AKRBP", "NHY", "TEL", "YAR", "MOWI", "STB", "SUBC", "SCATC"]

MACRO_FACTORS = {
    "EQNR": [
        {"text": "Brent oljepris", "sub": "Hver USD over 80 gir ca 0,8 mrd i EBITDA", "impact": "pos"},
        {"text": "Europeiske gasspriser", "sub": "TTF-priser styrer inntekter fra europeisk gass", "impact": "neg"},
        {"text": "Petroleumsbeskatning", "sub": "Marginalskatt på 78 % — politisk risikofaktor", "impact": "neg"},
        {"text": "USD/NOK kurs", "sub": "Inntekter i USD, kostnader delvis i NOK", "impact": "pos"},
        {"text": "Energy transition-tempo", "sub": "Press mot fossil virksomhet fra ESG-investorer", "impact": "neu"},
    ],
    "DNB": [
        {"text": "Norges Banks styringsrente", "sub": "Hver 0,25 pp = ca 500 mill i nettorentemargin", "impact": "pos"},
        {"text": "Boligprisutvikling", "sub": "Påvirker kredittap og etterspørsel etter boliglån", "impact": "pos"},
        {"text": "Norsk BNP-vekst", "sub": "Bedriftssektor-utlån vokser med økonomien", "impact": "pos"},
        {"text": "Regulatorisk kapitalkrav", "sub": "Basel IV og systemrisikopåslag", "impact": "neg"},
        {"text": "Arbeidsledighet", "sub": "Lav ledighet = lave kredittap", "impact": "pos"},
    ],
    "AKRBP": [
        {"text": "Brent oljepris", "sub": "Break-even under $30/fat — svært robust", "impact": "pos"},
        {"text": "Petroleumsbeskatning", "sub": "78 % marginalskatt — felles risiko med EQNR", "impact": "neg"},
        {"text": "USD/NOK kurs", "sub": "Inntekter i USD, investeringer delvis i NOK", "impact": "pos"},
        {"text": "Offshore riggtilgang", "sub": "Begrenset tilgang øker kostnader for Yggdrasil", "impact": "neg"},
        {"text": "Klimapolitikk (EU)", "sub": "Kan påvirke markedstilgang for norsk olje/gass", "impact": "neu"},
    ],
    "NHY": [
        {"text": "Aluminiumspris (LME)", "sub": "Hovedinntektsdriver — $1/tonn = 200 mill i EBITDA", "impact": "pos"},
        {"text": "Nordiske strømpriser", "sub": "Energy-segmentet drar nytte av høye priser", "impact": "pos"},
        {"text": "CO2-priser i EU (ETS)", "sub": "Premium for grønn aluminium øker", "impact": "pos"},
        {"text": "Kinesisk produksjon", "sub": "Kapasitet i Kina styrer global tilbudsside", "impact": "neg"},
        {"text": "Bauksittpriser", "sub": "Råvarekostnad — påvirker margin", "impact": "neg"},
    ],
    "TEL": [
        {"text": "Norsk inflasjon", "sub": "Påvirker prisjusteringer på abonnementer", "impact": "pos"},
        {"text": "Strømpriser", "sub": "Energi er stor kostnad for nettverk", "impact": "neg"},
        {"text": "Reguleringsregime", "sub": "Nkom og EU regulerer roaming og priser", "impact": "neu"},
        {"text": "Asiatiske valutakurser", "sub": "PKR, BDT, MMK — fortsatt eksponering", "impact": "neu"},
        {"text": "Norges Banks rente", "sub": "Påvirker gjeldsbetjening", "impact": "neu"},
    ],
    "YAR": [
        {"text": "Naturgasspriser", "sub": "Hovedinnsatsfaktor i ammoniakkproduksjon", "impact": "neg"},
        {"text": "Internasjonale gjødselpriser", "sub": "Hovedinntektsdriver — volatile", "impact": "neu"},
        {"text": "Globale matpriser", "sub": "Påvirker etterspørsel etter gjødsel", "impact": "pos"},
        {"text": "CO2-priser i EU", "sub": "Påvirker konkurranseforhold for grønn ammoniakk", "impact": "pos"},
        {"text": "Brasiliansk valuta (BRL)", "sub": "Stort marked for Yara", "impact": "neu"},
    ],
    "MOWI": [
        {"text": "Lakseprisen (spot)", "sub": "Over 80 NOK/kg gir rekordmarginer", "impact": "pos"},
        {"text": "Grunnrenteskatt", "sub": "25 % effektiv skatt reduserer netto resultat", "impact": "neg"},
        {"text": "Eksport til Kina/USA", "sub": "To av tre viktigste markeder — volumfølsomme", "impact": "neu"},
        {"text": "Fôrkostnader", "sub": "Soya og fiskemel — utgjør ca 40 % av kostnadene", "impact": "neg"},
        {"text": "EUR/NOK valutakurs", "sub": "Mesteparten av salget skjer i EUR og USD", "impact": "pos"},
    ],
    "STB": [
        {"text": "Norges Banks styringsrente", "sub": "Påvirker investeringsavkastning på buffere", "impact": "neu"},
        {"text": "Aksjemarkedet (OSEBX)", "sub": "Påvirker resultater i kapitalforvaltning", "impact": "pos"},
        {"text": "Demografi", "sub": "Aldrende befolkning øker etterspørsel etter pensjon", "impact": "pos"},
        {"text": "EU-regulering (Solvency II)", "sub": "Endringer kan påvirke kapitalkrav", "impact": "neu"},
        {"text": "ESG-fokus", "sub": "Strukturell trend gunstig for posisjonen", "impact": "pos"},
    ],
    "SUBC": [
        {"text": "Offshore investeringer", "sub": "Globalt over $200 mrd — sterkeste på 10 år", "impact": "pos"},
        {"text": "Brent oljepris", "sub": "Driver kapasitetsbeslutninger hos kunder", "impact": "pos"},
        {"text": "Havvind-utrulling i Europa", "sub": "EU-mål om 350 GW havvind innen 2050", "impact": "pos"},
        {"text": "USD-kurs", "sub": "Inntekter i USD, kostnader internasjonale", "impact": "pos"},
        {"text": "Råvarekostnader (stål)", "sub": "Påvirker prosjektmarginer", "impact": "neg"},
    ],
    "SCATC": [
        {"text": "Globale rentenivåer", "sub": "Fornybarprosjekter er sensitive til rente", "impact": "pos"},
        {"text": "Solcellepriser", "sub": "PV-moduler stadig billigere — gunstig", "impact": "pos"},
        {"text": "Politisk risiko fremvoksende markeder", "sub": "Egypt, Sør-Afrika, Brasil — utfordrende", "impact": "neg"},
        {"text": "EUR og lokale valutaer", "sub": "Inntekter i lokale, gjeld i EUR/USD", "impact": "neg"},
        {"text": "Klimapolitikk og subsidier", "sub": "COP-forhandlinger og lokale insentiver", "impact": "pos"},
    ],
}

COMPANY_FACTORS = {
    "EQNR": [
        {"text": "Produksjon på norsk sokkel", "sub": "Johan Sverdrup står for ~40 % av norsk produksjon", "impact": "pos"},
        {"text": "Ledig kapasitet på Troll", "sub": "Tillater fleksibel gassproduksjon etter pris", "impact": "pos"},
        {"text": "Fornybar-satsing (Hywind)", "sub": "Flyttende havvind — langsiktig vekstområde", "impact": "pos"},
        {"text": "Utbyttepolitikk", "sub": "Forpliktet til økende utbytte gjennom syklusen", "impact": "pos"},
        {"text": "Reservereplasement", "sub": "Må finne nye reserver for å opprettholde produksjon", "impact": "neg"},
    ],
    "DNB": [
        {"text": "Nettorentemargin (NIM)", "sub": "Over 1,95 % i Q1 — historisk høyt", "impact": "pos"},
        {"text": "Kredittaps-rate", "sub": "Bare 0,08 % — indikerer god kvalitet", "impact": "pos"},
        {"text": "Digital satsing (Vipps)", "sub": "DNB eier 47 % av Vipps MobilePay", "impact": "pos"},
        {"text": "Kapitaldekning (CET1)", "sub": "18,3 % gir stor utbyttekapasitet", "impact": "pos"},
        {"text": "Aktiv M&A-strategi", "sub": "Oppkjøp av Carnegie styrker meglervirksomheten", "impact": "pos"},
    ],
    "AKRBP": [
        {"text": "Johan Sverdrup-bidrag", "sub": "Ca 70 % av produksjonen, verdens billigste olje", "impact": "pos"},
        {"text": "Yggdrasil-prosjektet", "sub": "Oppstart 2027 — legger til 55 000 fat/dag", "impact": "pos"},
        {"text": "Produksjonskostnader", "sub": "Under $10/fat — laveste i sektoren", "impact": "pos"},
        {"text": "Utbyttepolitikk", "sub": "Forpliktet til $0,60 per aksje kvartalsvis", "impact": "pos"},
        {"text": "Hod og Valhall oppgradering", "sub": "Forlenger levetiden av viktige felter", "impact": "pos"},
    ],
    "NHY": [
        {"text": "Grønn aluminium-portefølje", "sub": "CIRCAL og REDUXA selger med 15-20 % premium", "impact": "pos"},
        {"text": "Vannkraftproduksjon", "sub": "Egen energi gir konkurransefortrinn", "impact": "pos"},
        {"text": "Hydrogen-satsing", "sub": "Joint ventures med Statkraft og Yara", "impact": "pos"},
        {"text": "Brasilianske operasjoner", "sub": "Alunorte og Albras — politisk risiko", "impact": "neu"},
        {"text": "Resirkulering", "sub": "Investering i closed-loop systemer", "impact": "pos"},
    ],
    "TEL": [
        {"text": "5G-utrulling i Norden", "sub": "Skal være ferdig 2027 — kapitalintensiv", "impact": "neu"},
        {"text": "Nordisk markedsposisjon", "sub": "Markedsleder i Norge og Sverige", "impact": "pos"},
        {"text": "Salg av asiatiske enheter", "sub": "Reduserer politisk risiko", "impact": "pos"},
        {"text": "Konkurranse fra Ice", "sub": "Presser marginene i Norge", "impact": "neg"},
        {"text": "Utbyttepolitikk", "sub": "Stabil — minst 9 kr per aksje", "impact": "pos"},
    ],
    "YAR": [
        {"text": "Clean ammonia-satsing", "sub": "Strategisk for shipping-drivstoff", "impact": "pos"},
        {"text": "Karbonfangst-prosjekt", "sub": "Senker karbonintensitet på produkter", "impact": "pos"},
        {"text": "Tett gassmarked i Europa", "sub": "Konkurransefortrinn for amerikanske rivaler", "impact": "neg"},
        {"text": "Brasiliansk markedsandel", "sub": "Ledende i et voksende marked", "impact": "pos"},
        {"text": "Utbyttedekning", "sub": "Kontantstrøm dekker ikke fullt nivå", "impact": "neg"},
    ],
    "MOWI": [
        {"text": "Biologisk produktivitet", "sub": "Dødelighet og tilvekst avgjør volum", "impact": "pos"},
        {"text": "MAB-kapasitet", "sub": "Maksimalt tillatt biomasse begrenser produksjon", "impact": "neu"},
        {"text": "Vertikal integrasjon", "sub": "Eier kjede fra rogn til foredlet produkt", "impact": "pos"},
        {"text": "Sykdoms- og lakselusrisiko", "sub": "ISA og PD kan utløse nedslaktinger", "impact": "neg"},
        {"text": "Investering i landbasert oppdrett", "sub": "Langsiktig bet på produksjon utenfor sjø", "impact": "neu"},
    ],
    "STB": [
        {"text": "Bærekraftig fondsprodukter", "sub": "40 % av nye salg er nå ESG-fond", "impact": "pos"},
        {"text": "Solvens-margin (178 %)", "sub": "Solid kapitalisering over kravet på 100 %", "impact": "pos"},
        {"text": "Forvaltningskapital", "sub": "Over 1 000 mrd kr — Nordens største", "impact": "pos"},
        {"text": "Bedriftsmarked-vekst", "sub": "Sterk innsalgsutvikling i bedriftsmarkedet", "impact": "pos"},
        {"text": "Digitale plattformer", "sub": "Investerer i selvbetjeningsløsninger", "impact": "pos"},
    ],
    "SUBC": [
        {"text": "Ordrebok (12 mrd USD)", "sub": "Rekordhøyt, dekker 18 måneder", "impact": "pos"},
        {"text": "Yggdrasil-kontrakt", "sub": "Strategisk prosjekt med Aker BP / Equinor", "impact": "pos"},
        {"text": "Havvind-segment", "sub": "Renewable EPCI vokser raskt", "impact": "pos"},
        {"text": "Fartøyflåten", "sub": "38 spesialfartøyer — kapitalintensiv", "impact": "neu"},
        {"text": "Marginer på fastpriskontrakter", "sub": "Prosjektrisiko ved store EPCI", "impact": "neg"},
    ],
    "SCATC": [
        {"text": "Portefølje i drift (4,2 GW)", "sub": "Kontantstrømgenererende installasjoner", "impact": "pos"},
        {"text": "Pipeline (15 GW)", "sub": "Vekstpotensial — men finansiering kreves", "impact": "pos"},
        {"text": "Gjeldsgrad", "sub": "Høy gjeld typisk — risiko ved stigende rente", "impact": "neg"},
        {"text": "Diversifisering geografisk", "sub": "Reduserer enkeltlands-risiko", "impact": "pos"},
        {"text": "Batterilagre-segmentet", "sub": "Vekstområde, men umoden teknologi", "impact": "neu"},
    ],
}

COMPETITORS = {
    "EQNR": [
        {"name": "Equinor (du)", "ticker": "EQNR", "mcap": "892 mrd", "pe": "7,4x", "div": "8,2 %", "roe": "22,1 %", "year": "+18 %", "rec": "Overvekt"},
        {"name": "Shell", "ticker": "SHEL", "mcap": "2 100 mrd", "pe": "8,1x", "div": "4,5 %", "roe": "16,8 %", "year": "+12 %", "rec": "Nøytral"},
        {"name": "BP", "ticker": "BP", "mcap": "1 100 mrd", "pe": "7,8x", "div": "5,3 %", "roe": "14,2 %", "year": "+8 %", "rec": "Nøytral"},
        {"name": "Aker BP", "ticker": "AKRBP", "mcap": "161 mrd", "pe": "6,9x", "div": "9,1 %", "roe": "24,3 %", "year": "+22 %", "rec": "Overvekt"},
        {"name": "TotalEnergies", "ticker": "TTE", "mcap": "1 500 mrd", "pe": "7,2x", "div": "5,8 %", "roe": "19,5 %", "year": "+15 %", "rec": "Overvekt"},
    ],
    "DNB": [
        {"name": "DNB Bank (du)", "ticker": "DNB", "mcap": "345 mrd", "pe": "9,2x", "div": "5,8 %", "roe": "15,2 %", "year": "+22 %", "rec": "Overvekt"},
        {"name": "Nordea Bank", "ticker": "NDA", "mcap": "420 mrd", "pe": "8,6x", "div": "6,1 %", "roe": "14,8 %", "year": "+15 %", "rec": "Overvekt"},
        {"name": "Swedbank", "ticker": "SWED-A", "mcap": "280 mrd", "pe": "7,9x", "div": "7,2 %", "roe": "16,1 %", "year": "+18 %", "rec": "Overvekt"},
        {"name": "SpareBank 1 SR", "ticker": "SRBNK", "mcap": "42 mrd", "pe": "8,4x", "div": "5,4 %", "roe": "13,2 %", "year": "+9 %", "rec": "Nøytral"},
        {"name": "SEB", "ticker": "SEB-A", "mcap": "310 mrd", "pe": "9,1x", "div": "6,3 %", "roe": "15,5 %", "year": "+12 %", "rec": "Nøytral"},
    ],
    "AKRBP": [
        {"name": "Aker BP (du)", "ticker": "AKRBP", "mcap": "161 mrd", "pe": "6,9x", "div": "9,1 %", "roe": "24,3 %", "year": "+22 %", "rec": "Overvekt"},
        {"name": "Equinor", "ticker": "EQNR", "mcap": "892 mrd", "pe": "7,4x", "div": "8,2 %", "roe": "22,1 %", "year": "+18 %", "rec": "Overvekt"},
        {"name": "Var Energi", "ticker": "VAR", "mcap": "80 mrd", "pe": "7,2x", "div": "11,2 %", "roe": "26,5 %", "year": "+14 %", "rec": "Overvekt"},
        {"name": "DNO", "ticker": "DNO", "mcap": "12 mrd", "pe": "5,8x", "div": "7,8 %", "roe": "19,2 %", "year": "−3 %", "rec": "Nøytral"},
        {"name": "OKEA", "ticker": "OKEA", "mcap": "3 mrd", "pe": "4,2x", "div": "14,5 %", "roe": "32,1 %", "year": "−8 %", "rec": "Nøytral"},
    ],
    "NHY": [
        {"name": "Norsk Hydro (du)", "ticker": "NHY", "mcap": "142 mrd", "pe": "11,8x", "div": "6,2 %", "roe": "11,4 %", "year": "+8 %", "rec": "Overvekt"},
        {"name": "Alcoa", "ticker": "AA", "mcap": "85 mrd", "pe": "13,2x", "div": "2,8 %", "roe": "9,5 %", "year": "+12 %", "rec": "Nøytral"},
        {"name": "Rio Tinto", "ticker": "RIO", "mcap": "900 mrd", "pe": "9,8x", "div": "7,4 %", "roe": "21,2 %", "year": "+15 %", "rec": "Overvekt"},
        {"name": "Boliden", "ticker": "BOL", "mcap": "95 mrd", "pe": "12,5x", "div": "4,8 %", "roe": "14,2 %", "year": "+5 %", "rec": "Nøytral"},
        {"name": "Yara Internat.", "ticker": "YAR", "mcap": "78 mrd", "pe": "14,5x", "div": "5,2 %", "roe": "8,8 %", "year": "−12 %", "rec": "Nøytral"},
    ],
    "TEL": [
        {"name": "Telenor (du)", "ticker": "TEL", "mcap": "167 mrd", "pe": "12,4x", "div": "7,8 %", "roe": "14,5 %", "year": "+2 %", "rec": "Nøytral"},
        {"name": "Telia", "ticker": "TELIA", "mcap": "105 mrd", "pe": "13,8x", "div": "8,2 %", "roe": "11,2 %", "year": "−5 %", "rec": "Nøytral"},
        {"name": "Vodafone", "ticker": "VOD", "mcap": "180 mrd", "pe": "11,5x", "div": "9,4 %", "roe": "10,8 %", "year": "+8 %", "rec": "Nøytral"},
        {"name": "Deutsche Tele.", "ticker": "DTE", "mcap": "1 200 mrd", "pe": "14,2x", "div": "4,5 %", "roe": "12,5 %", "year": "+15 %", "rec": "Overvekt"},
        {"name": "Tele2", "ticker": "TEL2", "mcap": "60 mrd", "pe": "15,1x", "div": "7,2 %", "roe": "13,8 %", "year": "+4 %", "rec": "Nøytral"},
    ],
    "YAR": [
        {"name": "Yara Internat. (du)", "ticker": "YAR", "mcap": "78 mrd", "pe": "14,5x", "div": "5,2 %", "roe": "8,8 %", "year": "−12 %", "rec": "Nøytral"},
        {"name": "CF Industries", "ticker": "CF", "mcap": "180 mrd", "pe": "11,2x", "div": "2,1 %", "roe": "15,8 %", "year": "+8 %", "rec": "Overvekt"},
        {"name": "Nutrien", "ticker": "NTR", "mcap": "290 mrd", "pe": "10,5x", "div": "4,2 %", "roe": "12,4 %", "year": "+5 %", "rec": "Overvekt"},
        {"name": "Mosaic", "ticker": "MOS", "mcap": "110 mrd", "pe": "9,8x", "div": "3,5 %", "roe": "14,1 %", "year": "+10 %", "rec": "Overvekt"},
        {"name": "ICL Group", "ticker": "ICL", "mcap": "85 mrd", "pe": "12,8x", "div": "6,8 %", "roe": "11,2 %", "year": "−4 %", "rec": "Nøytral"},
    ],
    "MOWI": [
        {"name": "Mowi (du)", "ticker": "MOWI", "mcap": "98 mrd", "pe": "14,2x", "div": "3,4 %", "roe": "12,8 %", "year": "−8 %", "rec": "Nøytral"},
        {"name": "SalMar", "ticker": "SALM", "mcap": "71 mrd", "pe": "15,1x", "div": "2,8 %", "roe": "11,4 %", "year": "−12 %", "rec": "Nøytral"},
        {"name": "Lerøy Seafood", "ticker": "LSG", "mcap": "28 mrd", "pe": "12,8x", "div": "4,1 %", "roe": "10,2 %", "year": "−5 %", "rec": "Nøytral"},
        {"name": "Grieg Seafood", "ticker": "GSF", "mcap": "9 mrd", "pe": "13,5x", "div": "3,2 %", "roe": "8,9 %", "year": "−18 %", "rec": "Undervekt"},
        {"name": "Bakkafrost", "ticker": "BAKKA", "mcap": "42 mrd", "pe": "16,3x", "div": "2,1 %", "roe": "13,5 %", "year": "+2 %", "rec": "Nøytral"},
    ],
    "STB": [
        {"name": "Storebrand (du)", "ticker": "STB", "mcap": "49 mrd", "pe": "11,2x", "div": "6,5 %", "roe": "10,8 %", "year": "+12 %", "rec": "Overvekt"},
        {"name": "Gjensidige", "ticker": "GJF", "mcap": "90 mrd", "pe": "13,5x", "div": "5,8 %", "roe": "14,2 %", "year": "+8 %", "rec": "Overvekt"},
        {"name": "Sampo", "ticker": "SAMPO", "mcap": "230 mrd", "pe": "12,8x", "div": "6,2 %", "roe": "13,5 %", "year": "+10 %", "rec": "Overvekt"},
        {"name": "Tryg", "ticker": "TRYG", "mcap": "85 mrd", "pe": "14,1x", "div": "5,4 %", "roe": "15,8 %", "year": "+5 %", "rec": "Nøytral"},
        {"name": "Topdanmark", "ticker": "TOP", "mcap": "38 mrd", "pe": "13,2x", "div": "6,8 %", "roe": "12,5 %", "year": "+3 %", "rec": "Nøytral"},
    ],
    "SUBC": [
        {"name": "Subsea 7 (du)", "ticker": "SUBC", "mcap": "52 mrd", "pe": "8,2x", "div": "4,5 %", "roe": "17,2 %", "year": "+28 %", "rec": "Overvekt"},
        {"name": "TechnipFMC", "ticker": "FTI", "mcap": "130 mrd", "pe": "10,5x", "div": "2,1 %", "roe": "14,8 %", "year": "+22 %", "rec": "Overvekt"},
        {"name": "Saipem", "ticker": "SPM", "mcap": "65 mrd", "pe": "12,8x", "div": "0 %", "roe": "11,2 %", "year": "+15 %", "rec": "Nøytral"},
        {"name": "Aker Solutions", "ticker": "AKSO", "mcap": "21 mrd", "pe": "7,8x", "div": "3,2 %", "roe": "15,5 %", "year": "+18 %", "rec": "Overvekt"},
        {"name": "Wood Group", "ticker": "WG", "mcap": "12 mrd", "pe": "14,2x", "div": "0 %", "roe": "8,5 %", "year": "+5 %", "rec": "Nøytral"},
    ],
    "SCATC": [
        {"name": "Scatec (du)", "ticker": "SCATC", "mcap": "13 mrd", "pe": "18,5x", "div": "1,2 %", "roe": "7,4 %", "year": "−15 %", "rec": "Nøytral"},
        {"name": "Ørsted", "ticker": "ORSTED", "mcap": "180 mrd", "pe": "22,5x", "div": "2,5 %", "roe": "6,8 %", "year": "−12 %", "rec": "Nøytral"},
        {"name": "EDP Renováveis", "ticker": "EDPR", "mcap": "180 mrd", "pe": "24,1x", "div": "0,8 %", "roe": "5,2 %", "year": "+5 %", "rec": "Nøytral"},
        {"name": "Iberdrola", "ticker": "IBE", "mcap": "850 mrd", "pe": "15,8x", "div": "4,5 %", "roe": "8,5 %", "year": "+10 %", "rec": "Overvekt"},
        {"name": "NEL ASA", "ticker": "NEL", "mcap": "12 mrd", "pe": "N/A", "div": "0 %", "roe": "−12 %", "year": "+18 %", "rec": "Nøytral"},
    ],
}
