"""
Konfigurasjon for Navigr - 10 største selskaper på Oslo Børs.

Brukerne starter med alle 10 som ankerflåte. De kan ta opp anker
og kaste anker for å tilpasse sin egen flåte.
"""

COMPANIES = {
    "EQNR": {
        "name": "Equinor ASA",
        "yahoo_ticker": "EQNR.OL",
        "sector": "Energi",
        "logo": "EQ",
        "domain": "equinor.com",
        "about": "Equinor ASA är Norges största energibolag, med huvudkontor i Stavanger. Bolaget arbetar med prospektering, produktion, transport, förädling och marknadsföring av petroleum och petroleumbaserade produkter, samt förnybar energi som havsbaserad vindkraft. Norska staten äger 67 % av bolaget.",
        "hq": "Stavanger",
        "founded": "1972",
        "employees": "23 100",
    },
    "DNB": {
        "name": "DNB Bank ASA",
        "yahoo_ticker": "DNB.OL",
        "sector": "Finans",
        "logo": "DN",
        "domain": "dnb.no",
        "about": "DNB Bank ASA är Norges största finanskoncern och en av de största bankerna i Norden. Bolaget erbjuder privat- och företagstjänster, kapitalförvaltning och försäkring. DNB äger 47 % av Vipps MobilePay och förvärvade nyligen mäklarhuset Carnegie.",
        "hq": "Bjørvika, Oslo",
        "founded": "1822",
        "employees": "10 200",
    },
    "AKRBP": {
        "name": "Aker BP ASA",
        "yahoo_ticker": "AKRBP.OL",
        "sector": "Energi",
        "logo": "AK",
        "domain": "akerbp.com",
        "about": "Aker BP ASA är ett norskt olje- och gasbolag som uteslutande verkar på norsk kontinentalsockel. Bolaget är en av de största operatörerna på norsk sockel och har lägst produktionskostnad i branschen. Johan Sverdrup-fältet är det viktigaste produktionsfältet.",
        "hq": "Fornebu",
        "founded": "2016",
        "employees": "2 100",
    },
    "NHY": {
        "name": "Norsk Hydro ASA",
        "yahoo_ticker": "NHY.OL",
        "sector": "Industri",
        "logo": "NH",
        "domain": "hydro.com",
        "about": "Norsk Hydro ASA är ett globalt aluminium- och förnybarbolag. Bolaget driver hela värdekedjan från bauxit-utvinning till produktion av aluminium, samt elproduktion från vattenkraft. Den norska staten äger 34 % av bolaget.",
        "hq": "Vækerø, Oslo",
        "founded": "1905",
        "employees": "34 000",
    },
    "TEL": {
        "name": "Telenor ASA",
        "yahoo_ticker": "TEL.OL",
        "sector": "Telekom",
        "logo": "TE",
        "domain": "telenor.com",
        "about": "Telenor ASA är ett norskt telekombolag som verkar i Norden och Asien. Bolaget levererar mobil- och fasttjänster till över 200 miljoner kunder. Norska staten är huvudägare med 54 %.",
        "hq": "Fornebu",
        "founded": "1855",
        "employees": "15 600",
    },
    "YAR": {
        "name": "Yara International ASA",
        "yahoo_ticker": "YAR.OL",
        "sector": "Industri",
        "logo": "YA",
        "domain": "yara.com",
        "about": "Yara International ASA är en av världens största producenter av mineralgödsel. Bolaget verkar i över 60 länder och har som mål att vara koldioxidneutralt till 2050.",
        "hq": "Vækerø, Oslo",
        "founded": "1905",
        "employees": "17 800",
    },
    "MOWI": {
        "name": "Mowi ASA",
        "yahoo_ticker": "MOWI.OL",
        "sector": "Sjømat",
        "logo": "MO",
        "domain": "mowi.com",
        "about": "Mowi ASA är världens största odlingsbolag för atlantlax. Bolaget verkar i Norge, Skottland, Kanada, Chile, Färöarna och Irland och är fullt vertikalt integrerat.",
        "hq": "Bergen",
        "founded": "1964",
        "employees": "15 000",
    },
    "STB": {
        "name": "Storebrand ASA",
        "yahoo_ticker": "STB.OL",
        "sector": "Finans",
        "logo": "ST",
        "domain": "storebrand.no",
        "about": "Storebrand ASA är en nordisk försäkrings- och finanskoncern som erbjuder pension, livförsäkring, skadeförsäkring, bank och kapitalförvaltning. Bolaget är en av Nordens största kapitalförvaltare med över 1 000 miljarder i förvaltat kapital.",
        "hq": "Lysaker",
        "founded": "1767",
        "employees": "2 200",
    },
    "SUBC": {
        "name": "Subsea 7 SA",
        "yahoo_ticker": "SUBC.OL",
        "sector": "Energi",
        "logo": "S7",
        "domain": "subsea7.com",
        "about": "Subsea 7 SA är ett globalt bolag som levererar undervattenskonstruktion för olje- och gasindustrin och förnybarindustrin till havs. Huvudfokus är på djupvattenutbyggnad och havsbaserade vindkraftsinstallationer.",
        "hq": "Luxembourg",
        "founded": "2002",
        "employees": "12 000",
    },
    "SCATC": {
        "name": "Scatec ASA",
        "yahoo_ticker": "SCATC.OL",
        "sector": "Fornybar energi",
        "logo": "SC",
        "domain": "scatec.com",
        "about": "Scatec ASA är ett norskt oberoende kraftproduktionsbolag som utvecklar, bygger, äger och driver solcellsparker, vattenkraftverk och batterilager. Bolaget verkar i över 15 länder med fokus på tillväxtmarknader.",
        "hq": "Karenslyst, Oslo",
        "founded": "2007",
        "employees": "700",
    },
}

INITIAL_FLEET = ["EQNR", "DNB", "AKRBP", "NHY", "TEL", "YAR", "MOWI", "STB", "SUBC", "SCATC"]

MACRO_FACTORS = {
    "EQNR": [
        {"text": "Brent oljepris", "sub": "Varje USD över 80 ger ca 0,8 mrd i EBITDA", "impact": "pos"},
        {"text": "Europeiska gaspriser", "sub": "TTF-priser styr intäkter från europeisk gas", "impact": "neg"},
        {"text": "Petroleumsbeskattning", "sub": "Marginalskatt på 78 % — politisk riskfaktor", "impact": "neg"},
        {"text": "USD/NOK kurs", "sub": "Intäkter i USD, kostnader delvis i NOK", "impact": "pos"},
        {"text": "Energiomställningstempo", "sub": "Tryck mot fossil verksamhet från ESG-investerare", "impact": "neu"},
    ],
    "DNB": [
        {"text": "Norges Banks styrränta", "sub": "Varje 0,25 pp = ca 500 mill i räntenettomarginal", "impact": "pos"},
        {"text": "Bostadsprisutveckling", "sub": "Påverkar kreditförluster och efterfrågan på bolån", "impact": "pos"},
        {"text": "Norsk BNP-tillväxt", "sub": "Företagssektorns utlåning växer med ekonomin", "impact": "pos"},
        {"text": "Regulatoriska kapitalkrav", "sub": "Basel IV och systemrisikopåslag", "impact": "neg"},
        {"text": "Arbetslöshet", "sub": "Låg arbetslöshet = låga kreditförluster", "impact": "pos"},
    ],
    "AKRBP": [
        {"text": "Brent oljepris", "sub": "Break-even under $30/fat — mycket robust", "impact": "pos"},
        {"text": "Petroleumsbeskattning", "sub": "78 % marginalskatt — gemensam risk med EQNR", "impact": "neg"},
        {"text": "USD/NOK kurs", "sub": "Intäkter i USD, investeringar delvis i NOK", "impact": "pos"},
        {"text": "Offshore riggtillgång", "sub": "Begränsad tillgång ökar kostnader för Yggdrasil", "impact": "neg"},
        {"text": "Klimatpolitik (EU)", "sub": "Kan påverka marknadstillträde för norsk olja/gas", "impact": "neu"},
    ],
    "NHY": [
        {"text": "Aluminiumpris (LME)", "sub": "Huvudintäktsdrivare — $1/ton = 200 mill i EBITDA", "impact": "pos"},
        {"text": "Nordiska elpriser", "sub": "Energy-segmentet drar nytta av höga priser", "impact": "pos"},
        {"text": "CO2-priser i EU (ETS)", "sub": "Premium för grön aluminium ökar", "impact": "pos"},
        {"text": "Kinesisk produktion", "sub": "Kapacitet i Kina styr global utbudssida", "impact": "neg"},
        {"text": "Bauxitpriser", "sub": "Råvarukostnad — påverkar marginalen", "impact": "neg"},
    ],
    "TEL": [
        {"text": "Norsk inflation", "sub": "Påverkar prisjusteringar på abonnemang", "impact": "pos"},
        {"text": "Elpriser", "sub": "Energi är en stor kostnad för nätverk", "impact": "neg"},
        {"text": "Regleringssystem", "sub": "Nkom och EU reglerar roaming och priser", "impact": "neu"},
        {"text": "Asiatiska valutakurser", "sub": "PKR, BDT, MMK — fortfarande exponering", "impact": "neu"},
        {"text": "Norges Banks ränta", "sub": "Påverkar skuldbetalning", "impact": "neu"},
    ],
    "YAR": [
        {"text": "Naturgaspriser", "sub": "Huvudinsatsfaktor i ammoniakproduktion", "impact": "neg"},
        {"text": "Internationella gödselpriser", "sub": "Huvudintäktsdrivare — volatila", "impact": "neu"},
        {"text": "Globala matpriser", "sub": "Påverkar efterfrågan på gödsel", "impact": "pos"},
        {"text": "CO2-priser i EU", "sub": "Påverkar konkurrensförhållanden för grön ammoniak", "impact": "pos"},
        {"text": "Brasiliansk valuta (BRL)", "sub": "Stor marknad för Yara", "impact": "neu"},
    ],
    "MOWI": [
        {"text": "Laxpris (spot)", "sub": "Över 80 NOK/kg ger rekordmarginaler", "impact": "pos"},
        {"text": "Grundrenteskatt", "sub": "25 % effektiv skatt minskar nettoresultatet", "impact": "neg"},
        {"text": "Export till Kina/USA", "sub": "Två av tre viktigaste marknader — volymsensitiva", "impact": "neu"},
        {"text": "Foderkostnader", "sub": "Soja och fiskmjöl — utgör ca 40 % av kostnaderna", "impact": "neg"},
        {"text": "EUR/NOK valutakurs", "sub": "Större delen av försäljningen sker i EUR och USD", "impact": "pos"},
    ],
    "STB": [
        {"text": "Norges Banks styrränta", "sub": "Påverkar investeringsavkastning på buffertar", "impact": "neu"},
        {"text": "Aktiemarknaden (OSEBX)", "sub": "Påverkar resultat i kapitalförvaltning", "impact": "pos"},
        {"text": "Demografi", "sub": "Åldrande befolkning ökar efterfrågan på pension", "impact": "pos"},
        {"text": "EU-reglering (Solvency II)", "sub": "Förändringar kan påverka kapitalkrav", "impact": "neu"},
        {"text": "ESG-fokus", "sub": "Strukturell trend gynnsam för positionen", "impact": "pos"},
    ],
    "SUBC": [
        {"text": "Offshoreinvesteringar", "sub": "Globalt över $200 mrd — starkaste på 10 år", "impact": "pos"},
        {"text": "Brent oljepris", "sub": "Driver kapacitetsbeslut hos kunder", "impact": "pos"},
        {"text": "Havsbaserad vind i Europa", "sub": "EU-mål om 350 GW havsbaserad vind till 2050", "impact": "pos"},
        {"text": "USD-kurs", "sub": "Intäkter i USD, kostnader internationella", "impact": "pos"},
        {"text": "Råvarukostnader (stål)", "sub": "Påverkar projektmarginaler", "impact": "neg"},
    ],
    "SCATC": [
        {"text": "Globala räntenivåer", "sub": "Förnybarsprojekt är räntekänsliga", "impact": "pos"},
        {"text": "Solcellspriser", "sub": "PV-moduler allt billigare — gynnsamt", "impact": "pos"},
        {"text": "Politisk risk tillväxtmarknader", "sub": "Egypten, Sydafrika, Brasilien — utmanande", "impact": "neg"},
        {"text": "EUR och lokala valutor", "sub": "Intäkter i lokala, skulder i EUR/USD", "impact": "neg"},
        {"text": "Klimatpolitik och subventioner", "sub": "COP-förhandlingar och lokala incitament", "impact": "pos"},
    ],
}

COMPANY_FACTORS = {
    "EQNR": [
        {"text": "Produktion på norsk sockel", "sub": "Johan Sverdrup svarar för ~40 % av norsk produktion", "impact": "pos"},
        {"text": "Ledig kapacitet på Troll", "sub": "Tillåter flexibel gasproduktion efter pris", "impact": "pos"},
        {"text": "Förnybarsatsning (Hywind)", "sub": "Flytande havsbaserad vind — långsiktigt tillväxtområde", "impact": "pos"},
        {"text": "Utdelningspolicy", "sub": "Åtagit sig att öka utdelning genom cykeln", "impact": "pos"},
        {"text": "Reserversättning", "sub": "Måste hitta nya reserver för att upprätthålla produktion", "impact": "neg"},
    ],
    "DNB": [
        {"text": "Räntenettomarginal (NIM)", "sub": "Över 1,95 % i Q1 — historiskt högt", "impact": "pos"},
        {"text": "Kreditförlustnivå", "sub": "Bara 0,08 % — indikerar god kvalitet", "impact": "pos"},
        {"text": "Digital satsning (Vipps)", "sub": "DNB äger 47 % av Vipps MobilePay", "impact": "pos"},
        {"text": "Kapitaltäckning (CET1)", "sub": "18,3 % ger stor utdelningskapacitet", "impact": "pos"},
        {"text": "Aktiv M&A-strategi", "sub": "Förvärv av Carnegie stärker mäklarverksamheten", "impact": "pos"},
    ],
    "AKRBP": [
        {"text": "Johan Sverdrup-bidrag", "sub": "Ca 70 % av produktionen, världens billigaste olja", "impact": "pos"},
        {"text": "Yggdrasil-projektet", "sub": "Start 2027 — tillför 55 000 fat/dag", "impact": "pos"},
        {"text": "Produktionskostnader", "sub": "Under $10/fat — lägst i sektorn", "impact": "pos"},
        {"text": "Utdelningspolicy", "sub": "Åtagit sig $0,60 per aktie kvartalsvis", "impact": "pos"},
        {"text": "Hod och Valhall-uppgradering", "sub": "Förlänger livslängden för viktiga fält", "impact": "pos"},
    ],
    "NHY": [
        {"text": "Grön aluminiumportfölj", "sub": "CIRCAL och REDUXA säljer med 15-20 % premium", "impact": "pos"},
        {"text": "Vattenkraftproduktion", "sub": "Egen energi ger konkurrensfördel", "impact": "pos"},
        {"text": "Vätesatsning", "sub": "Joint ventures med Statkraft och Yara", "impact": "pos"},
        {"text": "Brasilianska verksamheter", "sub": "Alunorte och Albras — politisk risk", "impact": "neu"},
        {"text": "Återvinning", "sub": "Investering i closed-loop-system", "impact": "pos"},
    ],
    "TEL": [
        {"text": "5G-utbyggnad i Norden", "sub": "Ska vara färdig 2027 — kapitalintensiv", "impact": "neu"},
        {"text": "Nordisk marknadsposition", "sub": "Marknadsledare i Norge och Sverige", "impact": "pos"},
        {"text": "Försäljning av asiatiska enheter", "sub": "Minskar politisk risk", "impact": "pos"},
        {"text": "Konkurrens från Ice", "sub": "Pressar marginaler i Norge", "impact": "neg"},
        {"text": "Utdelningspolicy", "sub": "Stabil — minst 9 kr per aktie", "impact": "pos"},
    ],
    "YAR": [
        {"text": "Clean ammonia-satsning", "sub": "Strategisk för sjöfartsbränsle", "impact": "pos"},
        {"text": "Koldioxidinfångningsprojekt", "sub": "Sänker koldioxidintensitet på produkter", "impact": "pos"},
        {"text": "Ansträngt gasmarknad i Europa", "sub": "Konkurrensfördel för amerikanska rivaler", "impact": "neg"},
        {"text": "Brasiliansk marknadsandel", "sub": "Ledande på en växande marknad", "impact": "pos"},
        {"text": "Utdelningstäckning", "sub": "Kassaflöde täcker inte fullt ut nivån", "impact": "neg"},
    ],
    "MOWI": [
        {"text": "Biologisk produktivitet", "sub": "Dödlighet och tillväxt avgör volym", "impact": "pos"},
        {"text": "MAB-kapacitet", "sub": "Maximalt tillåten biomassa begränsar produktion", "impact": "neu"},
        {"text": "Vertikal integration", "sub": "Äger kedjan från rom till förädlad produkt", "impact": "pos"},
        {"text": "Sjukdoms- och laxlusrisk", "sub": "ISA och PD kan utlösa nödslakt", "impact": "neg"},
        {"text": "Investering i landbaserad odling", "sub": "Långsiktigt bet på produktion utanför havet", "impact": "neu"},
    ],
    "STB": [
        {"text": "Hållbara fondprodukter", "sub": "40 % av ny försäljning är nu ESG-fonder", "impact": "pos"},
        {"text": "Solvensmarginal (178 %)", "sub": "Solid kapitalisering över kravet på 100 %", "impact": "pos"},
        {"text": "Förvaltat kapital", "sub": "Över 1 000 mrd kr — Nordens största", "impact": "pos"},
        {"text": "Företagsmarknadstillväxt", "sub": "Stark försäljningsutveckling på företagsmarknaden", "impact": "pos"},
        {"text": "Digitala plattformar", "sub": "Investerar i självbetjäningslösningar", "impact": "pos"},
    ],
    "SUBC": [
        {"text": "Orderbok (12 mrd USD)", "sub": "Rekordnivå, täcker 18 månader", "impact": "pos"},
        {"text": "Yggdrasil-kontrakt", "sub": "Strategiskt projekt med Aker BP / Equinor", "impact": "pos"},
        {"text": "Havsbaserat vindsegment", "sub": "Renewable EPCI växer snabbt", "impact": "pos"},
        {"text": "Fartygsflottan", "sub": "38 specialfartyg — kapitalintensiv", "impact": "neu"},
        {"text": "Marginaler på fastpriskontrakt", "sub": "Projektrisk vid stora EPCI", "impact": "neg"},
    ],
    "SCATC": [
        {"text": "Portfölj i drift (4,2 GW)", "sub": "Kassaflödesgenererande installationer", "impact": "pos"},
        {"text": "Pipeline (15 GW)", "sub": "Tillväxtpotential — men finansiering krävs", "impact": "pos"},
        {"text": "Skuldsättning", "sub": "Hög skuld typiskt — risk vid stigande ränta", "impact": "neg"},
        {"text": "Geografisk diversifiering", "sub": "Minskar risk för enskilda länder", "impact": "pos"},
        {"text": "Batterilager-segmentet", "sub": "Tillväxtområde, men omogen teknologi", "impact": "neu"},
    ],
}

COMPETITORS = {
    "EQNR": [
        {"name": "Equinor (du)", "ticker": "EQNR", "mcap": "892 mrd", "pe": "7,4x", "div": "8,2 %", "roe": "22,1 %", "year": "+18 %", "rec": "Övervikt"},
        {"name": "Shell", "ticker": "SHEL", "mcap": "2 100 mrd", "pe": "8,1x", "div": "4,5 %", "roe": "16,8 %", "year": "+12 %", "rec": "Neutral"},
        {"name": "BP", "ticker": "BP", "mcap": "1 100 mrd", "pe": "7,8x", "div": "5,3 %", "roe": "14,2 %", "year": "+8 %", "rec": "Neutral"},
        {"name": "Aker BP", "ticker": "AKRBP", "mcap": "161 mrd", "pe": "6,9x", "div": "9,1 %", "roe": "24,3 %", "year": "+22 %", "rec": "Övervikt"},
        {"name": "TotalEnergies", "ticker": "TTE", "mcap": "1 500 mrd", "pe": "7,2x", "div": "5,8 %", "roe": "19,5 %", "year": "+15 %", "rec": "Övervikt"},
    ],
    "DNB": [
        {"name": "DNB Bank (du)", "ticker": "DNB", "mcap": "345 mrd", "pe": "9,2x", "div": "5,8 %", "roe": "15,2 %", "year": "+22 %", "rec": "Övervikt"},
        {"name": "Nordea Bank", "ticker": "NDA", "mcap": "420 mrd", "pe": "8,6x", "div": "6,1 %", "roe": "14,8 %", "year": "+15 %", "rec": "Övervikt"},
        {"name": "Swedbank", "ticker": "SWED-A", "mcap": "280 mrd", "pe": "7,9x", "div": "7,2 %", "roe": "16,1 %", "year": "+18 %", "rec": "Övervikt"},
        {"name": "SpareBank 1 SR", "ticker": "SRBNK", "mcap": "42 mrd", "pe": "8,4x", "div": "5,4 %", "roe": "13,2 %", "year": "+9 %", "rec": "Neutral"},
        {"name": "SEB", "ticker": "SEB-A", "mcap": "310 mrd", "pe": "9,1x", "div": "6,3 %", "roe": "15,5 %", "year": "+12 %", "rec": "Neutral"},
    ],
    "AKRBP": [
        {"name": "Aker BP (du)", "ticker": "AKRBP", "mcap": "161 mrd", "pe": "6,9x", "div": "9,1 %", "roe": "24,3 %", "year": "+22 %", "rec": "Övervikt"},
        {"name": "Equinor", "ticker": "EQNR", "mcap": "892 mrd", "pe": "7,4x", "div": "8,2 %", "roe": "22,1 %", "year": "+18 %", "rec": "Övervikt"},
        {"name": "Var Energi", "ticker": "VAR", "mcap": "80 mrd", "pe": "7,2x", "div": "11,2 %", "roe": "26,5 %", "year": "+14 %", "rec": "Övervikt"},
        {"name": "DNO", "ticker": "DNO", "mcap": "12 mrd", "pe": "5,8x", "div": "7,8 %", "roe": "19,2 %", "year": "−3 %", "rec": "Neutral"},
        {"name": "OKEA", "ticker": "OKEA", "mcap": "3 mrd", "pe": "4,2x", "div": "14,5 %", "roe": "32,1 %", "year": "−8 %", "rec": "Neutral"},
    ],
    "NHY": [
        {"name": "Norsk Hydro (du)", "ticker": "NHY", "mcap": "142 mrd", "pe": "11,8x", "div": "6,2 %", "roe": "11,4 %", "year": "+8 %", "rec": "Övervikt"},
        {"name": "Alcoa", "ticker": "AA", "mcap": "85 mrd", "pe": "13,2x", "div": "2,8 %", "roe": "9,5 %", "year": "+12 %", "rec": "Neutral"},
        {"name": "Rio Tinto", "ticker": "RIO", "mcap": "900 mrd", "pe": "9,8x", "div": "7,4 %", "roe": "21,2 %", "year": "+15 %", "rec": "Övervikt"},
        {"name": "Boliden", "ticker": "BOL", "mcap": "95 mrd", "pe": "12,5x", "div": "4,8 %", "roe": "14,2 %", "year": "+5 %", "rec": "Neutral"},
        {"name": "Yara Internat.", "ticker": "YAR", "mcap": "78 mrd", "pe": "14,5x", "div": "5,2 %", "roe": "8,8 %", "year": "−12 %", "rec": "Neutral"},
    ],
    "TEL": [
        {"name": "Telenor (du)", "ticker": "TEL", "mcap": "167 mrd", "pe": "12,4x", "div": "7,8 %", "roe": "14,5 %", "year": "+2 %", "rec": "Neutral"},
        {"name": "Telia", "ticker": "TELIA", "mcap": "105 mrd", "pe": "13,8x", "div": "8,2 %", "roe": "11,2 %", "year": "−5 %", "rec": "Neutral"},
        {"name": "Vodafone", "ticker": "VOD", "mcap": "180 mrd", "pe": "11,5x", "div": "9,4 %", "roe": "10,8 %", "year": "+8 %", "rec": "Neutral"},
        {"name": "Deutsche Tele.", "ticker": "DTE", "mcap": "1 200 mrd", "pe": "14,2x", "div": "4,5 %", "roe": "12,5 %", "year": "+15 %", "rec": "Övervikt"},
        {"name": "Tele2", "ticker": "TEL2", "mcap": "60 mrd", "pe": "15,1x", "div": "7,2 %", "roe": "13,8 %", "year": "+4 %", "rec": "Neutral"},
    ],
    "YAR": [
        {"name": "Yara Internat. (du)", "ticker": "YAR", "mcap": "78 mrd", "pe": "14,5x", "div": "5,2 %", "roe": "8,8 %", "year": "−12 %", "rec": "Neutral"},
        {"name": "CF Industries", "ticker": "CF", "mcap": "180 mrd", "pe": "11,2x", "div": "2,1 %", "roe": "15,8 %", "year": "+8 %", "rec": "Övervikt"},
        {"name": "Nutrien", "ticker": "NTR", "mcap": "290 mrd", "pe": "10,5x", "div": "4,2 %", "roe": "12,4 %", "year": "+5 %", "rec": "Övervikt"},
        {"name": "Mosaic", "ticker": "MOS", "mcap": "110 mrd", "pe": "9,8x", "div": "3,5 %", "roe": "14,1 %", "year": "+10 %", "rec": "Övervikt"},
        {"name": "ICL Group", "ticker": "ICL", "mcap": "85 mrd", "pe": "12,8x", "div": "6,8 %", "roe": "11,2 %", "year": "−4 %", "rec": "Neutral"},
    ],
    "MOWI": [
        {"name": "Mowi (du)", "ticker": "MOWI", "mcap": "98 mrd", "pe": "14,2x", "div": "3,4 %", "roe": "12,8 %", "year": "−8 %", "rec": "Neutral"},
        {"name": "SalMar", "ticker": "SALM", "mcap": "71 mrd", "pe": "15,1x", "div": "2,8 %", "roe": "11,4 %", "year": "−12 %", "rec": "Neutral"},
        {"name": "Lerøy Seafood", "ticker": "LSG", "mcap": "28 mrd", "pe": "12,8x", "div": "4,1 %", "roe": "10,2 %", "year": "−5 %", "rec": "Neutral"},
        {"name": "Grieg Seafood", "ticker": "GSF", "mcap": "9 mrd", "pe": "13,5x", "div": "3,2 %", "roe": "8,9 %", "year": "−18 %", "rec": "Undervikt"},
        {"name": "Bakkafrost", "ticker": "BAKKA", "mcap": "42 mrd", "pe": "16,3x", "div": "2,1 %", "roe": "13,5 %", "year": "+2 %", "rec": "Neutral"},
    ],
    "STB": [
        {"name": "Storebrand (du)", "ticker": "STB", "mcap": "49 mrd", "pe": "11,2x", "div": "6,5 %", "roe": "10,8 %", "year": "+12 %", "rec": "Övervikt"},
        {"name": "Gjensidige", "ticker": "GJF", "mcap": "90 mrd", "pe": "13,5x", "div": "5,8 %", "roe": "14,2 %", "year": "+8 %", "rec": "Övervikt"},
        {"name": "Sampo", "ticker": "SAMPO", "mcap": "230 mrd", "pe": "12,8x", "div": "6,2 %", "roe": "13,5 %", "year": "+10 %", "rec": "Övervikt"},
        {"name": "Tryg", "ticker": "TRYG", "mcap": "85 mrd", "pe": "14,1x", "div": "5,4 %", "roe": "15,8 %", "year": "+5 %", "rec": "Neutral"},
        {"name": "Topdanmark", "ticker": "TOP", "mcap": "38 mrd", "pe": "13,2x", "div": "6,8 %", "roe": "12,5 %", "year": "+3 %", "rec": "Neutral"},
    ],
    "SUBC": [
        {"name": "Subsea 7 (du)", "ticker": "SUBC", "mcap": "52 mrd", "pe": "8,2x", "div": "4,5 %", "roe": "17,2 %", "year": "+28 %", "rec": "Övervikt"},
        {"name": "TechnipFMC", "ticker": "FTI", "mcap": "130 mrd", "pe": "10,5x", "div": "2,1 %", "roe": "14,8 %", "year": "+22 %", "rec": "Övervikt"},
        {"name": "Saipem", "ticker": "SPM", "mcap": "65 mrd", "pe": "12,8x", "div": "0 %", "roe": "11,2 %", "year": "+15 %", "rec": "Neutral"},
        {"name": "Aker Solutions", "ticker": "AKSO", "mcap": "21 mrd", "pe": "7,8x", "div": "3,2 %", "roe": "15,5 %", "year": "+18 %", "rec": "Övervikt"},
        {"name": "Wood Group", "ticker": "WG", "mcap": "12 mrd", "pe": "14,2x", "div": "0 %", "roe": "8,5 %", "year": "+5 %", "rec": "Neutral"},
    ],
    "SCATC": [
        {"name": "Scatec (du)", "ticker": "SCATC", "mcap": "13 mrd", "pe": "18,5x", "div": "1,2 %", "roe": "7,4 %", "year": "−15 %", "rec": "Neutral"},
        {"name": "Ørsted", "ticker": "ORSTED", "mcap": "180 mrd", "pe": "22,5x", "div": "2,5 %", "roe": "6,8 %", "year": "−12 %", "rec": "Neutral"},
        {"name": "EDP Renováveis", "ticker": "EDPR", "mcap": "180 mrd", "pe": "24,1x", "div": "0,8 %", "roe": "5,2 %", "year": "+5 %", "rec": "Neutral"},
        {"name": "Iberdrola", "ticker": "IBE", "mcap": "850 mrd", "pe": "15,8x", "div": "4,5 %", "roe": "8,5 %", "year": "+10 %", "rec": "Övervikt"},
        {"name": "NEL ASA", "ticker": "NEL", "mcap": "12 mrd", "pe": "N/A", "div": "0 %", "roe": "−12 %", "year": "+18 %", "rec": "Neutral"},
    ],
}
